### ISSUE TITLE
Show only CS:GO VAC bans?

### ISSUE THREAD

**Issue by jmartty** [jung3o/VacStatus#102]
I just tested and the site will report a VAC ban no matter what game it is on. Would it be possible to only report VAC bans gotten on CS:GO? It seems using https://lab.xpaw.me/steam_api_documentation.html#ICheatReportingService_RequestVacStatusForUser_v1 it should be possible

**Comment by jung3o** [comment]
What goes under `session id`? I keep getting forbidden. it's telling me to verify my `key=` param

**Comment by jmartty** [comment]
Yeah, I had the same issue when testing it. No idea :/

**Comment by wartab** [comment]
It seems to me that this is an API used by game servers themselves in order to know whether they should accept people to be playing on them or not. And this session id is probably the session id of the server.

**Comment by jung3o** [comment]
Yeah that makes more sense.. I'll be closing this then.
