### ISSUE TITLE
Not the correct Steam account showing on a list (+visual bug on this row, too)

### ISSUE THREAD

**Issue by wartab** [jung3o/VacStatus#103]
If you check my list number 14454, it shows - at least for me - the following user 
https://vacstat.us/u/76561197989918174

The date for the VAC Ban says "Nov 30 -0001" in the list page.
Screenshot:
![list](https://cloud.githubusercontent.com/assets/9607577/9194996/e603041c-401f-11e5-82a1-2ce53c2296c7.gif)

Also, I never added this account to the list (I don't know if there was someone else before or if it just randomly got added).

**Comment by jung3o** [comment]
It seems like it was added at the same time with `lord` and `shazin.fr`

**Comment by wartab** [comment]
Pretty sure I didn't add this guy to my list as he doesn't even play anymore and doesn't own CSGO.
Also this weird date formatting leads me to think that there is another underlying problem.

**Comment by jung3o** [comment]
I've been searching for answers, but I can't seem to recreate this or figure out whats wrong. sorry.

I'll close this unless there is some new information
