### ISSUE TITLE
Community bans trigger notifications but does not show on lists.

### ISSUE THREAD

**Issue by Kezxo** [jung3o/VacStatus#108]
Community bans can be a bit confusing for the reasons in the title, you have to check the names in the notifications, find the person with the same name if they didn't change it and then click their profiles to see that they where not VAC or game banned as the notification said.

Also there is no date for community bans on the profiles. Have they stopped appearing on steam profiles now also?

**Comment by jung3o** [comment]
that's weird. there shouldnt be any reason community and trade bans notify you via email/pushbullet. can you link the profile of the person that's been notified?

**Comment by Kezxo** [comment]
https://vacstat.us/u/76561198085320193
https://vacstat.us/u/76561198021904571

Got a pushbullet notice for these two.

**Comment by jung3o** [comment]
Closing because it's been a while since it has been reported
