### ISSUE TITLE
API Connection Error - appears to be timeout related

### ISSUE THREAD

**Issue by skarlsen** [jung3o/VacStatus#112]
Hi

I'm having trouble loading my list with the list id 6398.
It consistently doesn't load, showing "This list is empty" and "error: api_conn_err" when previewing the response in Chrome. I believe the error might be timeout-related, as my list is rather large, containing 444 users. A test list with 1 user works as intended.

**Comment by jung3o** [comment]
That error shows up when profiles could not be loaded from steam API. I need to setup a better system for when that happens...
