### ISSUE TITLE
Adding new profiles to list don't work

### ISSUE THREAD

**Issue by psychob** [jung3o/VacStatus#113]
I want to add new profiles to track, but when i try to pass:

    # userid name uniqueid connected ping loss state rate
    #  5 3 "+KeNNyS+" STEAM_1:0:147113805 44:05 109 0 active 128000
    #  7 5 "Tytus.KKK" STEAM_1:0:123258158 44:05 67 0 active 80000
    #  8 6 "ReeVE" STEAM_1:0:50854912 44:05 118 0 active 80000
    #  9 7 "Kalinka" STEAM_1:0:145046959 44:05 96 4 active 128000
    # 10 8 "status" STEAM_1:1:116540056 44:05 77 0 active 80000
    # 11 9 "sG.Titan ScreaMy" STEAM_1:0:94074865 44:05 90 0 active 80000
    # 24 12 "Dope Chef" STEAM_1:0:40159775 06:54 59 0 active 80000

Website informs that: "list is empty".

Adding profile "per url" don't work too, for example:

    http://steamcommunity.com/profiles/76561198040585278/

produces: "list is empty" too.

I Am missing something?

**Comment by jung3o** [comment]
where are you trying to add these profiles from? directly on the list or from search?

**Comment by psychob** [comment]
main site -> look up users, i tried from list page, but was the same result. I checked steam browser, and then firefox.

After you posted i checked again, and it's now working :confused: But i swear, it wasn't minute ago.
