### ISSUE TITLE
Unable to search users (or add to a list)

### ISSUE THREAD

**Issue by Jigoku** [jung3o/VacStatus#114]
For the past 2 days i have this problem when pasting a list of steam profile links:
![s25](https://cloud.githubusercontent.com/assets/1535179/10735969/7baa2e14-7c02-11e5-80b7-3b117c753a0f.png)

**Comment by jung3o** [comment]
how many are you searching for? I see in the logs multiple times that php is timing out. I've updated the time limit. I have an idea to kind of fix this issue, but that will take a while. for now I suggest searching for maximum of 10? at a time

**Comment by Jigoku** [comment]
Sorry forgot to mention. This has been happening with a single lookup aswell (most i've tried has only been 3). I did at first suspect a browser issue with plugins (blocking scripts etc) but have ruled that out by trying a different browser.

For example, these 3 valid profiles do not return any results:
http://steamcommunity.com/profiles/76561198054165430/
http://steamcommunity.com/profiles/76561198171009430/
http://steamcommunity.com/profiles/76561198220580841/

Although some other recent players i've played against, do return results. It just seems to be the suspicious ones that i want to track, are the ones that cannot be searched or added to a list... odd?

**Comment by jung3o** [comment]
I know what's happening. I'm not requesting to the steam api with the new players im looking for via search. I'll fix this tonight, but i gtg to class right now.Quick fix for now would be going to https://vacstat.us/u/76561198054165430 and then looking up the user via search. 
sorry about that. 


     On Monday, October 26, 2015 5:15 PM, Ricky Thomson <notifications@github.com> wrote:
   

 Sorry forgot to mention. This has been happening with a single lookup aswell (most i've tried has only been 3). I did at first suspect a browser issue with plugins (blocking scripts etc) but have ruled that out by trying a different browser.For example, these 3 valid profiles do not return any results:
http://steamcommunity.com/profiles/76561198054165430/
http://steamcommunity.com/profiles/76561198171009430/
http://steamcommunity.com/profiles/76561198220580841/Although some other recent players i've played against, do return results. It just seems to be the suspicious ones that i want to track, are the ones that cannot be searched or added to a list... odd?—

**Comment by Jigoku** [comment]
Ah, great that works for now. I guess i should close this?

**Comment by jung3o** [comment]
Nah, I'll close it once I get it fixed
