### ISSUE TITLE
Readme file: run migration - add explanation

### ISSUE THREAD

**Issue by lightonflux** [jung3o/VacStatus#31]
From the readme:

> Run `php artisan migrate` to run migration

Does that mean you have to run it in any case? Or only if you migrate to a new version?

Could you please add a sentence that explains why you need to do it and what it does? So that inexperienced new users that don't know the artisan cli, know why they are executing the command.

**Comment by jung3o** [comment]
I linked laravel docs on read me. migration is to update the database and at that moment (that step) it's to create the tables.

Now and then when new features come up that requires update on database, you can run the command `php artisan migrate` to stay up to date with the sql database structure.
