### ISSUE TITLE
REST API to add profiles to a list

### ISSUE THREAD

**Issue by daddz** [jung3o/VacStatus#32]
Is it possible for you to add an endpoint so people can add profiles to their list through third-party tools?

Something like this that accepts requests:
```
POST https://vacstat.us/l/<id>/<other_id>/
```
with the steamid as POST data.

**Comment by jung3o** [comment]
I'll see what I can do. the whole point of this website was for me to learn laravel.

I wasn't really thinking about rest api and such nor did I know what that was at the time.

**Comment by daddz** [comment]
Nice to hear!

After skimming through the Laravel docs here are some ideas I had:
* Let users generate a random token to authenticate
   * Maybe another option in the User settings?
   * Let users invalidate tokens
* Add a route to accept POST requests for adding profiles to a list
   * __/l/\<list_id\>/\<id\>/__ or
   * __/l/\<list_id\>/\<id\>/add_profile__ or
   * the one you currently use __/list/user/add__
* Inputs for steamid and usertoken
   * check if token belongs to list owner to prevent misuse

Sadly my PHP knowledge is a thing of the past. (switched away after 5.0)

I may help you out with this when I find some time.
