### ISSUE TITLE
Data truncated for column 'seen' at row 1

### ISSUE THREAD

**Issue by jsifuentes** [jung3o/VacStatus#57]
Are you sure `seen` in `profile_old_alias` is suppose to be an int(11)?

I am getting the following after deploying VacStatus on my Mac and attempting to sign in with Steam. It's attempting to insert a timestamp into an int(11) field. Is the migration incorrectly making `seen` an int(11)?

```
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'seen' at row 1 (SQL: insert into `profile_old_alias` (`profile_id`, `seen`, `seen_alias`, `updated_at`, `created_at`) values (1, 2015-04-07 00:00:00, STEAM_NAME, 2015-04-07 14:28:00, 2015-04-07 14:28:00))
```

**Comment by jung3o** [comment]
that's awkward. I remember making it a timestamp not an int :/

**Comment by jung3o** [comment]
I need to create a new migration that alters `profile_old_alias`

it would be something like. 

```DB::statement('ALTER TABLE `profile_old_alias` MODIFY `seen` TIMESTAMP CURRENT_TIMESTAMP;');```

**Comment by jsifuentes** [comment]
Will do. I'll work on it in a few.

**Comment by jsifuentes** [comment]
A pull request has been made to fix this issue. This issue will be closed when the pull request is merged and the fix is verified.

**Comment by jsifuentes** [comment]
The pull request has been merged :)
