### ISSUE TITLE
Import from recently played with players

### ISSUE THREAD

**Issue by RikuXan** [jung3o/VacStatus#63]
I'm not sure if the Steam API allows this, but an import feature from one's recently played with players (http://steamcommunity.com/id/STEAMID/friends/players/) would be great.

**Comment by jung3o** [comment]
The only way that I know of is to copy and paste the source code of that webpage.The web api is limited. But that's a lot of work assuming the webpage won't change anytime soon.

**Comment by RikuXan** [comment]
That's a shame with the API, thanks for the answer.

**Comment by jung3o** [comment]
you're welcome to write up a regex for it

**Comment by RikuXan** [comment]
Might do so, I'm gonna post here if I get to it.

**Comment by RikuXan** [comment]
What would you need actually? Profile link, SteamID, SteamID64?

**Comment by jung3o** [comment]
steamid64 would be ideal. but they can all be converted. Just note, converting profile link would be the slowest. I convert steamid64 to the new u-id u:1:xxx it can be converted just by subtracting `76561197960265728`

see: [VacStatus\Steam\Steam](https://github.com/jung3o/VacStatus/blob/6e52ed5fe69ec383cdbd0ccdf54193417ee04021/app/Steam/Steam.php#L50)

**Comment by RikuXan** [comment]
Okay, turns out the page structure is very clear and the IDs are nicely syntactically separated, so `name="friends\[([0-9]{17})]"` should capture every SteamID64 on the page.

**Comment by jung3o** [comment]
Cool. But do we want ALL of the users in the page? Also, we're talking about `/coplay/` right? not `/players/`

**Comment by RikuXan** [comment]
Right, `/coplay/`. 
What filtering attributes would you propose? Unfortunately the page itself gives only very little information about the context of the encounter with a player (teammate/opponent, public/ranked etc.). 
One possibility I can think of would be presenting the user with a checkmark list after the parsing (The list can get quite big if a user plays on a public server for a while).
Another possibility would be to filter by game, e.g. you could allow only players from CSGO matches.
Anything you had in mind specifically?

**Comment by jung3o** [comment]
here's a really rough expression of what I was thinking of https://regex101.com/r/vT5pP0/1
obviously we would be grabbing all the id's under that 1 game

**Comment by RikuXan** [comment]
Ok, so how do you want to check which game the user wants to add?
Parse for games first and then let him choose with a list?

**Comment by jung3o** [comment]
yeah that sounds good

**Comment by RikuXan** [comment]
Alright, then we need two regexes, one that parses for games played and one that extracts all players from a given game.
One thing to note is that there are no IDs given in the code to identify matches, so we have to use the time played for that since it is the only unique attribute. Another thing to note is that the time played may look different, depending on the user's locale, so it shouldn't get parsed.
Third thing is that by parsing player IDs from the friendCheckbox, it automatically ignores players that are already on your friend list (which is reasonable I think, if someone on your friend list gets banned I think you'd notice).

Match parsing: https://regex101.com/r/zS0pJ4/1

For the player parrsing I'm currently thinking of a way to do it but I'm coming up short. As much as I like regexes, I feel like they may not be the best tool for this job, simply due to the structure of HTML, but maybe I'm just to inexperienced with them. Do you mind using an HTML/DOM parser rather than regex? I think PHP has a few good ones built-in.

**Comment by jung3o** [comment]
I have no problem using DOM parsers. Never used it on PHP though.

**Comment by RikuXan** [comment]
I'll try to write something up

**Comment by RikuXan** [comment]
Alright, here's the code: http://pastebin.com/aviUUg6e
It's basically just two functions and an example on how to use them:

getAllMatches: takes a DOMDocument as a parameter (which you will probably create from POST data I guess) and returns an array consisting of all the matches found with their game, time played (in a trimmed format) and the untrimmed time played to be used as a key to identify the match.

getMatchPlayers: takes a DOMDocument and the aforementioned untrimmed time key as parameters and returns an array consisting of SteamID64s of all players involved in the match who are not yet on your friendlist.

I excuse any coding faux pas, I normally don't write PHP and haven't in a very long time.

**Comment by daddz** [comment]
I tried to to this myself and ran into the following problems/ideas:
- requires to be logged into steam. so you need the cookie/fake the browser and login if you want to access '/coplay' from outside your browser.
- ignore games with more than 9 players (non-competitive)
- track game length (e.g. ignore games shorter than 10 mins)
- track game timestamps to prevent duplicate submits

Have you tackled any of them yet?

**Comment by RikuXan** [comment]
a) The way we thought of it a user would have to paste the site's source code into a text box to import the players (Cookie spoofing is not a good idea imo, security-wise it's very unprofessional, also probably forbidden as a form of account sharing).

b) I wouldn't necessarily limit it to competitive games (or CSGO for that matter), a user being able to choose the games for which he wants to add players makes more sense imo (though it would probably be a good idea to display the amount of players that participated in the match selection form).

c) Not really necessary imo, see b)

d) I haven't seen any duplicates matches in my list, however if there were some, I would assume they would get filtered out when all of the players were added to the big list to check against VAC.

**Comment by daddz** [comment]
a) My goal is to remove as many manual steps as possible - so copy/pasting the source of the page seems like a - meh - way to do it.
Maybe it could work on the vacstat.us page itself by requesting the coplay page in the users browser context.
b) True that. I only play CSGO on steam so I didn't include other games yet.
d) The games/players that have been submitted already shouldn't show up in the form anymore

**Comment by jung3o** [comment]
regarding (a), we can try and create iframe, but that would require user to be logged in steam web client. Even though a user might be logged into vacstatus with steam, they can still log off of steam afterwards. I think the only way is to give user a direction on how to do it.

When users are added to the list, I check for any duplicates. I already have a "mass add" part done on the backend where you can just feed it steamid64 bit and the list id to add users.

**Comment by jung3o** [comment]
@RikuXan I played around with the code and it's great! Something you should change is from heredoc to nowdoc. That's because heredoc calls the PHP variables when it shouldn't be. You can change it to nowdoc just by adding single quotes around `HTML` -> `<<<'HTML'`

**Comment by RikuXan** [comment]
Ok, I revised the code a little, here's the new version: http://pastebin.com/ecCMXF8A
I added the player count in the match data to get a quicker look on what where competitive matches and what were not.
However due to the fact that if someone dis- and reconnects during a match, they are listed twice (or more, depending on the number of reconnects) I had to parse the players already to check for duplicates. Because of this, I mashed both functions together so that the player data gets nested into the matches array. This also let me remove the unique matchTimeKey as there is no need to relate the two at a later stage anymore.
I also changed the literal to nowdoc as you suggested, although that should not matter in the long run since the data won't come from a literal.

**Comment by RikuXan** [comment]
Concerning the iframe story: If I'm not mistaken you should not be able to read the source of the embedded iframe due to the same origin policy. So that should be out of the question.
Without OAuth or something similar there is very little chance of getting the data automatically.

**Comment by ncla** [comment]
You could create a user script or extension that would periodically check
coplay page and submit data to Vacstatus API. Otherwise this seems like a
chore for a user.

**Comment by jsifuentes** [comment]
Be aware that Steam does not let you see other player's coplay list. With VacStatus, VacStatus cannot retrieve someone else's coplay without their cookies. The only way to retrieve the coplay list is through the web browser, it looks like. :( This feature may be a hit-and-miss. It would be great if Steam put a little more development effort in their Web API though.

**Comment by jsifuentes** [comment]
Also @ncla's idea isn't too bad, but it still requires effort from the user to constantly import their recently played into VacStatus. It's not very... efficient. But that seems to be the best way to implement this feature thus far.

**Comment by RikuXan** [comment]
A user script sounds like a good idea, I have no experience whatsoever in writing one though.
I feel as though that this is something that can be done after the basic functionality works and there is voiced demand for better usability.

**Comment by ncla** [comment]
A workflow for the extension could be something like this:

1) Extension checks every 45 minutes (average match time) for /coplay in the background and stores the data (player IDs, time when match occured, logged in users profile ID..) for each match in local storage

2) Have a page on vacstatus.com (/playedwith/ for example) where it would display all the data: how to install extension, display data stored from storage, or simply tell the user the extension is installed and running

3) You could select which matches you would like to import to a list or check against for any banned players

**Comment by arnaudbey** [comment]
+1 for this feature. If I manage to motivate myself, i could give a hand !

**Comment by arnaudbey** [comment]
it's quite a dirty draft but it extract well players profile URL (and print them in the footer)
https://gist.github.com/arnaudbey/31d3570cf4f70bab0c6b

**Comment by ncla** [comment]
There are two flaws with the script:

1) It fails to fetch all pages when the pagination has more than 4 pages
2) I am not sure, but I think VacStatus has to resolve the ID URL to Steam profile number, which costs an API request to Volvo. Instead you could extract profile number from DOM.

[](http://i.imgur.com/HLFJO3Q.png)

**Comment by nikosalonen** [comment]
I made a Chrome extension for this purpose: https://chrome.google.com/webstore/detail/add-to-vacstatus/jjjnkpdfhgfdimbcfonlpglhjkcbgign


Source here: https://github.com/nikosalonen/addtovacstatus

**Comment by jung3o** [comment]
I just played around with the extension and it's really neat and it's a great start.

**Comment by jung3o** [comment]
I'm learning how to make chrome extensions and here's some of my progress. I'm planning to show all of the recent games and then user can click on it to see more players. I'm still not 100% sure how I'm going to allow users to add people to list.

Right Now I'm thinking about having a button to the each match and each players for the person to add.

here's what I have so far.
![http://i.imgur.com/h8I5L60.png](http://i.imgur.com/h8I5L60.png)

**Comment by jung3o** [comment]
I completed the project so far. It fetches from coplay and you can just add it via extension

video of how it works: http://a.pomf.se/udopku.mp4

store: https://chrome.google.com/webstore/detail/vacstatus-chrome/odonflpjdomgpbcdgofdilbmalkejhbo

repo: https://github.com/jung3o/VacStatus-Chrome

**Comment by ncla** [comment]
Judging by the video it looks good. :+1: 

Perhaps move the interaction with recently played players list to an actual page on Vacstat.us? The 'generate key' part seems unnecessary step to take for user.

I'll check out the code later. :)

**Comment by jung3o** [comment]
I'm not so sure about doing that since each match can have a lot of players and sometimes ive seen pages get to 11 pages long on coplay. Which is slow already just trying to get 2 pages.

The private key is an api key for the user. I need it when people add players to their list.
