### ISSUE TITLE
Number of "tracked by" bugged on Most Tracked

### ISSUE THREAD

**Issue by jung3o** [jung3o/VacStatus#65]
sometimes you'd see 0 under "tracked by" which is incorrect because they're up there since they're the most tracked to begin with.

**Comment by jsifuentes** [comment]
I've noticed this as well, and was going to attempt to look into it. If you find a fix for it and want to fix it, leave a comment so I don't also attempt to make a fix. If I find a fix, I'll also comment back and take this issue.

**Comment by jung3o** [comment]
I've been trying to find issue. I'm going to be assuming I missed a spot when retrieving cache somewhere. Can't seem to find it.

**Comment by jung3o** [comment]
fixed on latest update
