### ISSUE TITLE
Profiles will null names do not display correctly on lists

### ISSUE THREAD

**Issue by antmldr** [jung3o/VacStatus#71]
Bit of an edge case, but it seems players that don't have a name set (not sure how this is possible, but I suppose there are ways of setting it as such) need a placeholder in lists or they become unclickable.

Example: https://steamcommunity.com/profiles/76561198172357170 on this list: https://vacstat.us/list/5444

Looking at the code, the <a> tag is being generated correctly, but it ends up having no content thus unclickable, e.g.
```html
<a class="" href="/u/76561198172357170" target="_blank" data-reactid=".0.2.0.0.1.0.1.$0.1.2">‏</a>
```

**Comment by jung3o** [comment]
It's technically not blank. that one profile seems to be using `&rlm;`
![http://i.imgur.com/9nK9DOy.png](http://i.imgur.com/9nK9DOy.png)

**Comment by antmldr** [comment]
Much nicer fix than a placeholder, good idea. Gw on the site :)
