### ISSUE TITLE
Add players to list by match-sharing code

### ISSUE THREAD

**Issue by SM411** [jung3o/VacStatus#84]
Suggestion: Add players to list by match-sharing code

Match-sharing code could be found under Watch->Your matches ->Watch scoreboard

**Comment by ncla** [comment]
Is that even possible? Isn't the URL used to download the demo? Unless you want the site to download the demo, extract it and then parse it, which is pretty ridiculous.

Alternatively you can get player IDs from the /friends/coplay page on Steam, see #69.
