### ISSUE TITLE
Check for unbans?

### ISSUE THREAD

**Issue by Kezxo** [jung3o/VacStatus#85]
You know for all those users who say they will get unbanned because it was a mistake.
Maybe it already works? Does the lists check for bans or does it check for changes to the ban statuses?

**Comment by jung3o** [comment]
it checks for any changes and will unban. You won't receive any email notification for unban though.

**Comment by Kezxo** [comment]
No chance for adding notifications for unbans?

**Comment by jung3o** [comment]
not at this moment. I have other things I want to work on.
It could be a possibility in the future.

**Comment by Kezxo** [comment]
Ok, thanks for the response. GJ on the site.
