### ISSUE TITLE
latest vac ban list after donation for 5$

### ISSUE THREAD

**Issue by eintier** [jung3o/VacStatus#88]
hi, it doesnt go to more then 100

**Comment by jung3o** [comment]
that has nothing to do with donation.

**Comment by eintier** [comment]
oh i thought if you donate you can watch more because
Change User Limit to 1500 per list	$5.00
https://vacstat.us/LIST/latest/vac

**Comment by jung3o** [comment]
Sorry about the misunderstanding. That's only for your own personal lists.

**Comment by eintier** [comment]
ah, ok, maybe in the future :-)
keep on the good work, thank you , love the site
