### ISSUE TITLE
Donator tag not showing

### ISSUE THREAD

**Issue by dotNNJ** [jung3o/VacStatus#89]
Hi,
Your contact page seems to be blank, so this is the next best place.

It seems there is a bug in your donation display system. I donated yesterday:

https://vacstat.us/donate I'm on the top of the recent donations list at the time of posting.

However, my profile does not have a donator tag/notice on it:
https://vacstat.us/u/76561198104472813

Hopefully you can resolve it :)

**Comment by jung3o** [comment]
Seems like you got the donator tag on the profile. It was probably cache that was not showing it
