### ISSUE TITLE
Friend list throws list_no_permission (list type: Friends Only)

### ISSUE THREAD

**Issue by christophlsa** [jung3o/VacStatus#93]
On the Lists Screen I can see the list of one of my friends which is of the type "Friends Only". If I open this List I get the error "list_no_permission".

* friends list: https://vacstat.us/list/8073
* my profile: https://vacstat.us/u/76561197961070391

**Comment by jung3o** [comment]
this issue should be fixed now 823886e1b6588e53ca779debd8da34000ba003af

**Comment by christophlsa** [comment]
works :+1:
