### ISSUE TITLE
VAC ban date bugged in list

### ISSUE THREAD

**Issue by maximilianjenders** [jung3o/VacStatus#97]
In one of my lists, the VAC ban date is displayed incorrectly:

https://imgur.com/kTUvPzW

https://vacstat.us/list/20806 page 14

**Comment by jung3o** [comment]
You're not giving any info. Please link me the list and profile of the user that is `glitched`. The list can be private.

For now im closing this.

**Comment by maximilianjenders** [comment]
sorry, I hit enter before filling out the description, but edited it in a minute ago.

**Comment by jung3o** [comment]
I think this issue might be from when I first introduced better vac ban system in the database. I probably made everyone's ban date something like `0000-00-00 00:00:00`.

I recently updated the code to not check on the date. I totally forgot about this.

**Comment by maximilianjenders** [comment]
Thanks for your fast reply. Unfortunately, the Vac ban date is still displayed as "Nov 30 -0001" in the list for me.
