### ISSUE TITLE
Email alerts for newly banned tracked players not being sent out?

### ISSUE THREAD

**Issue by maximilianjenders** [jung3o/VacStatus#98]
I have several people on a list that have been vac banned recently (https://vacstat.us/list/20806#, TimCLS 12.07., ✘✘✘ aka Führer 11.07., MIA KHALIFA 09.07., Ellie 05.07. ). 

I am subscribed to that list and have a valid email set up on my profile. However, I have not received any emails that the players have been banned (not in spam as well). 

I used to receive those emails, I received the last one on 20.06.

**Comment by jung3o** [comment]
oops. it looks like I forgot to uncomment the part.
https://github.com/jung3o/VacStatus/blob/master/app/Console/Commands/ListChecker.php#L29

I'll get this working asap. thanks for the report.
